version: '3.9'

services:
  backend:
    build: ./backend
    container_name: video_sent_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: video_sent_frontend
    ports:
      - "5671:80"
    depends_on:
      - backend
    restart: unless-stopped
