# Generated by Django 5.2.4 on 2025-10-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='downloader.video')),
            ],
        ),
    ]
