# Generated by Django 5.2.4 on 2025-10-28 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speech_to_text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('sentiment', models.CharField(choices=[('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('EXCELLENT', 'Excellent')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('summary', models.TextField(max_length=255)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sentiments', to='speech_to_text.transcript')),
            ],
        ),
    ]
